-- Trendx service accounts. Run through scripts/bootstrap-service-accounts.sh.
-- Values are supplied with psql -v; no credentials belong in this file.
\set ON_ERROR_STOP on

-- The script creates databases and roles before invoking this file.
\connect :ANALYTICS_DB_NAME
REVOKE ALL ON DATABASE :"ANALYTICS_DB_NAME" FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT CONNECT ON DATABASE :"ANALYTICS_DB_NAME" TO :"ANALYTICS_DB_USER", :"GRAFANA_DB_USER", :"MIGRATION_USER";
GRANT USAGE, CREATE ON SCHEMA public TO :"MIGRATION_USER";
GRANT USAGE ON SCHEMA public TO :"ANALYTICS_DB_USER", :"GRAFANA_DB_USER";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO :"ANALYTICS_DB_USER";
GRANT SELECT ON ALL TABLES IN SCHEMA public TO :"GRAFANA_DB_USER";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO :"ANALYTICS_DB_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE :"MIGRATION_USER" IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"ANALYTICS_DB_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE :"MIGRATION_USER" IN SCHEMA public
  GRANT SELECT ON TABLES TO :"GRAFANA_DB_USER";

\connect :AIRFLOW_DB_NAME
REVOKE ALL ON DATABASE :"AIRFLOW_DB_NAME" FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT CONNECT, TEMPORARY ON DATABASE :"AIRFLOW_DB_NAME" TO :"AIRFLOW_DB_USER";
GRANT CONNECT ON DATABASE :"AIRFLOW_DB_NAME" TO :"MIGRATION_USER";
GRANT USAGE, CREATE ON SCHEMA public TO :"AIRFLOW_DB_USER", :"MIGRATION_USER";

\connect :MLFLOW_DB_NAME
REVOKE ALL ON DATABASE :"MLFLOW_DB_NAME" FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT CONNECT, TEMPORARY ON DATABASE :"MLFLOW_DB_NAME" TO :"MLFLOW_DB_USER";
GRANT CONNECT ON DATABASE :"MLFLOW_DB_NAME" TO :"MIGRATION_USER";
GRANT USAGE, CREATE ON SCHEMA public TO :"MLFLOW_DB_USER", :"MIGRATION_USER";

-- Grafana has no PostgreSQL write privileges. It uses the analytics database
-- only through its read-only datasource role.
